# lto makes linking the app pretty slow
# But it seems to be required to get LLVM bitcode .o objects.

[profile.release]
lto = true

[profile.dev]
lto = true

[workspace]
members = [
    "app",
    "plugin",
    "header",
]
