#!/bin/sh

if [ -e ./clang/ ]
then
    echo "Looks like the clang linux toolchain is already present."
    exit
fi

wget --continue https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
sha512sum --check ./clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz.sha512sum

BIN="clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-/bin"

echo "Extracting required binaries... (This may take a few minutes.)"
# FIXME: Do we need to extract everything?
# Are the binaries statically linked?
tar --verbose --extract -f ./clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz \
    "$BIN/llvm-dis" \
    "$BIN/ld.lld" \
    "$BIN/lld-link"

mv "clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-" clang/
